name: Fullstack CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./fontend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./fontend

      - name: Build frontend
        run: npm run build
        working-directory: ./fontend

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: ./cypress/videos

  build-backend:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.2-eclipse-temurin-20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./backend

      - name: Build backend
        run: mvn clean package
        working-directory: ./backend

      - name: Upload backend jar
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: target/*.jar
